### PR TITLE
[AKS] create .ssh folder before creating ssh public key

### LINKED ISSUE #19943: [AKS] New-AzAKSCluster does not generate SSH key pair
### Description

The following command does not generate the SSH Key for AKS Cluster

```
New-AzAksCluster -ResourceGroupName $rg.ResourceGroupName -Name 'aksautoscale' -NodeCount 1 
-NodeVmSetType VirtualMachineScaleSets -LoadBalancerSku standard -EnableNodeAutoScaling -NodeMinCount 1 
-NodeMaxCount 3 -GenerateSshKey
```
(Note: code wrapped for readability) 

### Issue script & Debug output

```PowerShell
PS C:\Users\xxxxx\test\AKS> $MyAKSCluster = New-AzAksCluster -ResourceGroupName $rg.ResourceGroupName -Name 'aksautoscale' -NodeCount 1 -NodeVmSetType VirtualMachineScaleSets -LoadBalancerSku standard -EnableNodeAutoScaling -NodeMinCount 1 -NodeMaxCount 3 -GenerateSshKey
DEBUG: 2:26:26 PM - NewAzureRmAks begin processing with ParameterSet 'defaultParameterSet'.
DEBUG: 2:26:26 PM - using account id 'xxxxxxxxxxx'...
DEBUG: 2:26:26 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
DEBUG: Generating public/private rsa key pair.

DEBUG: 2:26:33 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
New-AzAksCluster: Could not find SSH public key in default path 'C:\Users\xxxxx\.ssh\id_rsa.pub' which is required for creating k8s cluster. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys or https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows for generating a key pair manually; or you could try to add switch parameter -GenerateSshKey during calling New-AzAksCluster which will automatically generate SSH key file if you have ssh-keygen installed.
DEBUG: 2:26:33 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Aks:5.0.0; CommandName: New-AzAksCluster; PSVersion: 7.2.7; IsSuccess: False; Duration: 00:00:06.5193965; Exception: Could not find SSH public key in default path 'C:\Users\xxxxx\.ssh\id_rsa.pub' which is required for creating k8s cluster. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys or https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows for generating a key pair manually; or you could try to add switch parameter -GenerateSshKey during calling New-AzAksCluster which will automatically generate SSH key file if you have ssh-keygen installed.;
DEBUG: 2:26:33 PM - NewAzureRmAks end processing.
```
```


### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
```


### Module versions

```PowerShell
PS C:\Users\xxxx\test\AKS> Get-Module Az*   

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     5.0.0                 Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, Get-AzAksNodePool…}
Script     6.3.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
New-AzAksCluster: Could not find SSH public key in default path 'C:\Users\xxxxx\.ssh\id_rsa.pub' which is required for creating k8s cluster. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys or https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows for generating a key pair manually; or you could try to add switch parameter -GenerateSshKey during calling New-AzAksCluster which will automatically generate SSH key file if you have ssh-keygen installed.
```

### PR DESCRIPTION
**Pull request by YanaXu**
## Description

Fix #19943 .
Create .ssh folder if it does not exist before creating ssh public key file.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by wyunchi-ms — APPROVED** [review]

File: src/Aks/Aks/Commands/NewAzureRmAks.cs [hunk 1]
```diff
@@ -266,7 +266,11 @@ private void PreValidate()
 
         private string GenerateSshKeyValue()
         {
-            String generateSshKeyPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".ssh", "id_rsa"); ;
+            String generateSshKeyFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".ssh");
+            if (!Directory.Exists(generateSshKeyFolder)) {
+                Directory.CreateDirectory(generateSshKeyFolder);
+            }
+            String generateSshKeyPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ".ssh", "id_rsa");
```
Comment (wyunchi-ms) [inline src/Aks/Aks/Commands/NewAzureRmAks.cs:273]: It will be better if reuse `generateSshKeyFolder` here
