### PR TITLE
[AKS] fix a bug in zip on windows

### LINKED ISSUE #20734: Invoke-AzAksRunCommand with subdirectories in -CommandContextAttachment doesn't work due to the use of backslashes as path separators
### Description

A directory, which contains kubernetes manifests on the top level, can be applied to an AKS cluster using `Invoke-AzAksRunCommand -CommandContextAttachment <path> -Command "kubectl apply -f ."`

However, if the directory contains sub-directories, then Invoke-AzAksRunCommand fails with the misleading error message: 
**Failed to run command due to cluster perf issue, container command-<some-guid> in aks-command namespace did not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).**

Invoke-AzAksRunCommand creates a pod with an init-container, which does the following:
 - command:                                                                                                                                                                                                        
      - bash                                                                                                                                                                                                          
      - -c                                                                                                                                                                                                            
      - echo extracting user context && **unzip -o /cmd-context/context.zip -d /command-state/command-files**                                                                                                               
         && echo copying default SA && cp -r /var/run/secrets/kubernetes.io/serviceaccount                                                                                                                               
         /command-state/k8s-identity && echo wait for AAD token && inotifywait -e modify                                                                                                                                 
        -t 60 /command-state/k8s-identity/token && sleep 5s
 
By looking into the logs of the init-container created by `Invoke-AzAksRunCommand `, we noticed that it fails with exit code 1 after executing the `unzip` step. According to the [man page](https://linux.die.net/man/1/unzip) of `unzip` , it returns 1 when there are errors OR warnings. By inspecting the logs, we see indeed such a warning, which reads: **warning:  /cmd-context/context.zip appears to use backslashes as path separators**. We believe that this root cause of the issue. 

### Issue script & Debug output

```PowerShell
Invoke-AzAksRunCommand -ResourceGroupName "" -Name "" `
-CommandContextAttachment "directory with top level k8s manifests" `
-Command "kubectl apply -f ." `
-Force # this works fine

Invoke-AzAksRunCommand -ResourceGroupName "" -Name "" `
-CommandContextAttachment "directory with sub-directories containing k8s manifests" `
-Command "kubectl apply -f . --recursive" `
-Force # this fails
```


### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.8
PSEdition                      Core
GitCommitId                    7.2.8
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```


### Module versions

```PowerShell
ModuleType Version    PreRelease Name
---------- -------    ---------- ---- 
Script     9.0.1                 Az

ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     5.1.0                 Az.Aks
```


### Error output

```PowerShell
RequestId      : <>
Message        : Failed to run command due to cluster perf issue, container command-93cd5d2981594abab3e9a06ae14a7c2f in aks-command namespace did not start within 30s on your  
                 cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).
ServerMessage  : KubernetesOperationError: Failed to run command due to cluster perf issue, container command-93cd5d2981594abab3e9a06ae14a7c2f in aks-command namespace did     
                 not start within 30s on your cluster, retry may helps. If issue persist, you may need to tune your cluster with better performance (larger node/paid tier).    
                 (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {BadRequest}
RequestMessage : {POST <clusterId>}
InvocationInfo : {Invoke-AzAksRunCommand}
Line           : Invoke-AzAksRunCommand -ResourceGroupName "" `

Position       : At C:\Development\Invoke-AzAksRunCommand bug repro\Deploy-Manifests.ps1:1 char:1
                 + Invoke-AzAksRunCommand -ResourceGroupName "" `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.ContainerService.ManagedClustersOperations.BeginRunCommandWithHttpMessagesAsync(String resourceGroupName, String
                 resourceName, RunCommandRequest requestPayload, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ContainerService.ManagedClustersOperations.RunCommandWithHttpMessagesAsync(String resourceGroupName, String resourceName,     
                 RunCommandRequest requestPayload, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ContainerService.ManagedClustersOperationsExtensions.RunCommandAsync(IManagedClustersOperations operations, String
                 resourceGroupName, String resourceName, RunCommandRequest requestPayload, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ContainerService.ManagedClustersOperationsExtensions.RunCommand(IManagedClustersOperations operations, String
                 resourceGroupName, String resourceName, RunCommandRequest requestPayload)
                    at Microsoft.Azure.Commands.Aks.RunAzureRmAksCommand.<ExecuteCmdlet>b__42_0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String        
                 target, Action action, Func`1 useShouldContinue)
                    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String
                 target, Action action)
                    at Microsoft.Azure.Commands.Aks.RunAzureRmAksCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

### PR DESCRIPTION
**Pull request by YanaXu**
## Description

Fix #20734 .
According to the [Zip file spec](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) section 4.4.17.1, the path MUST only use forward slashes.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

File: src/Aks/Aks/Commands/RunAzureRmAksCommand.cs [hunk 1]
```diff
@@ -154,7 +154,7 @@ private string GetCommandContext()
                 {
                     foreach (string filepath in filesToAttach)
                     {
-                        var relativePath = filepath.Replace(rootDirectory, "").Trim('/').Trim('\\');
+                        var relativePath = filepath.Replace(rootDirectory, "").Replace('\\', '/').Trim('/');
```
Comment (BethanyZhou) [inline src/Aks/Aks/Commands/RunAzureRmAksCommand.cs:157]: Should we use System.IO.Path.DirectorySeparatorChar to meet separator definitions in different OSs? BTW, please add change log for your change.

Comment (YanaXu) [reply src/Aks/Aks/Commands/RunAzureRmAksCommand.cs:157]: The changelog is updated. Can't update "/" to System.IO.Path.DirectorySeparatorChar because Zip Spec does not support "\" but only "/".

File: src/Aks/Aks/ChangeLog.md [hunk 2]
```diff
@@ -20,6 +20,7 @@
 ## Upcoming Release
 * Added parameter `-AadProfile` for `New-AzAksCluster` and `Set-AzAksCluster`
 * Added parameter `-NodeHostGroupID` for `New-AzAksCluster` and parameter `-HostGroupID` for `New-AzAksNodePool`
+* Fixed the issue that Invoke-AzAksRunCommand will fail when the directory for parameter CommandContextAttachment contains sub-directories. [#20734]
```
Comment (BethanyZhou) [inline src/Aks/Aks/ChangeLog.md:23]: Please insert change log between L20-L21

**Review by BethanyZhou — APPROVED** [review]
LGTM
