### PR TITLE
Fix issue `Connect-AzAccount` fail in multi-threaded execution

### LINKED ISSUE #11201: ADAL Tracing causes synchronization errors in multi-threaded execution
## Steps to reproduce

Invoking a script like this that does multiple logins in parallel in the same AppDomain
```powershell
for( $i = 0; $i -lt 10; $i++) {if ($i % 2 -eq 0) {Start-ThreadJob {param([pscredential]$crd) try {Set-Sub c9cbd920-c00c-427c-852b-8aaf38badaeb $crd} catch {Resolve-AzError -Last} } -InitializationScript { Disable-AzContextAutosave -Scope Process| Out-Null; function Set-Sub { param([string]$sub, [pscredential]$crd); $prof = Connect-AzAccount -ErrorAction Stop -ServicePrincipal -Credential $crd -Tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 -Subscription $sub; if ($sub -eq $prof.Context.Subscription.Id) {Write-Host "Success"} else {Write-Error ("$sub does not match" + $prof.Context.Subscription.Id)}}} -ArgumentList $crd}
else {Start-ThreadJob {param([pscredential]$crd) try { Set-Sub 2c224e7e-3ef5-431d-a57b-e71f4662e3a6 $crd} catch {Resolve-AzError}} -InitializationScript { Disable-AzContextAutosave -Scope Process | Out-Null; function Set-Sub { param([string]$sub, [pscredential]$crd); $prof = Connect-AzAccount -ErrorAction Stop -ServicePrincipal -Credential $crd -Tenant 72f988bf-86f1-41af-91ab-2d7cd011db47 -Subscription $sub ; if ($sub -eq $prof.Context.Subscription.Id) {Write-Host "SUccess"} else {Write-Error ("$sub does not match" + $prof.Context.Subscription.Id)}}} -ArgumentList $crd}}

```
results in an error like this:

```
Message        : Collection was modified; enumeration operation may not execute.
StackTrace     :    at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
                    at Microsoft.Azure.Commands.Common.Authentication.AzureSessionInitializer.AdalSession.WriteToTraceListeners(String message)
                    at Microsoft.Azure.Commands.Common.Authentication.AdalLogger.AdalCompositeLogger.Log(LogLevel level, String message, Boolean containsPII)
                    at Microsoft.IdentityModel.Clients.ActiveDirectory.LoggerCallbackHandler.ExecuteCallback(LogLevel level, String message, Boolean containsPii)
                    at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.LoadFromCacheCommon(CacheQueryData cacheQueryData, CallState callState)
                    at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.LoadFromCacheAsync(CacheQueryData cacheQueryData, CallState callState)
                    at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
                    at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenForClientCommonAsync(String resource, ClientKey clientKey)
                    at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, ClientCredential clientCredential)
                    at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.AcquireTokenWithSecret(AdalConfiguration config, String appId, SecureString appKey)
                    at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.GetAccessToken(AdalConfiguration config, String promptBehavior, Action`1 promptAction, String
                 userId, SecureString password, String credentialType)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString
                 password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString
                 password, String promptBehavior, Action`1 promptAction)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String
                 subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
                    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.InvalidOperationException
InvocationInfo : {Connect-AzAccount}
```

Which is caused by this line of code:

https://github.com/Azure/azure-powershell/blob/master/src/Accounts/Authentication/AzureSessionInitializer.cs#L265

We can resolve this by using a pattern more like this, since the collection is threadsafe, but the resulting enumerator is not:

```
for (int i = 0; i < AuthenticationTraceListeners.Count; ++i)
                {
                    try
                    {
                        var trace = AuthenticationTraceListeners[i] as TraceListener;
                        trace.WriteLine(message);
                    }
                    catch { }
                }
```
## Environment data

not needed

## Module versions

not needed

## Debug output

see above

## Error output

see description

### PR DESCRIPTION
**Pull request by isra-fel**
## Description

Fix #11201 (more details in the issue)
Tested manually with 50 threads connecting to two accounts, all succeded.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

File: src/Accounts/Authentication/AzureSessionInitializer.cs [hunk 1]
```diff
@@ -254,18 +254,25 @@ public override SourceLevels AuthenticationTraceSourceLevel
...
             private void WriteToTraceListeners(string message)
             {
-                foreach (var listener in AuthenticationTraceListeners)
+                for (var i = 0; i < AuthenticationTraceListeners.Count; ++i) // don't use foreach, enumerator is not thread safe
                 {
-                    var trace = listener as TraceListener;
-                    trace.WriteLine(message);
+                    try
+                    {
+                        var trace = AuthenticationTraceListeners[i] as TraceListener;
```
Comment (dingmeng-xue) [inline src/Accounts/Authentication/AzureSessionInitializer.cs:269]: `as TraceListener` is not required.

Comment (isra-fel) [reply src/Accounts/Authentication/AzureSessionInitializer.cs]: Good point. Removed type conversion and combined two lines together. Thanks
