### PR TITLE
[AppService]: fix #21820 Fixed Set-AzWebApp isue with `Set-AzWebApp` when piping in Get-AzWebApp object

### LINKED ISSUE #21820: Set-AzWebApp returns badrequest when piping in Get-AzWebApp object
### Description

I have an issue when trying to update a app service using Set-AzWebApp with an object retrieved using Get-AzWebApp, at first i thought i was causing the issue with my changes that happen between calling get-azwebapp and set-azwebapp, but even if i make no changes it still errors. This used to work. I also tried updating to latest az modules but that made no difference, so I'm guessing the issue is in the api end.

If i run this simple 2 lines of code it errors with a badrequest

$web = Get-AzWebApp -ResourceGroupName <resourcegroup> -Name <name> -ErrorAction SilentlyContinue
$web = $web | Set-AzWebApp 

### Issue script & Debug output

```PowerShell
DEBUG: 20:00:39 - SetAzureWebAppCmdlet begin processing with ParameterSet 'S2'.
DEBUG: 20:00:39 - using account id 'xxxx@xxxxx.co.uk'...
DEBUG: 20:00:39 - [ConfigManager] Got [False] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxx@xxxxx.co.uk', environment: 'AzureCloud', tenant: 'tenantGUID'
DEBUG: 20:00:39 - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 20:00:39 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'tenantGUID', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxxxx.co.uk'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - 3130248b-88de-4b05-8802-11c024864855] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - 3130248b-88de-4b05-8802-11c024864855] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - 3130248b-88de-4b05-8802-11c024864855] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - 3130248b-88de-4b05-8802-11c024864855] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - 3130248b-88de-4b05-8802-11c024864855] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - 3130248b-88de-4b05-8802-11c024864855] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z] Found 2 cache accounts and 0 broker accountsDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z] Returning 2 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] MSAL 
MSAL.NetCore with assembly version '4.49.1.0'. CorrelationId(eb098419-7727-4576-b567-99b8e1a41374)
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374]      
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - eb098419-7727-4576-b567-99b8e1a41374
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] Access token is not expired. Returning the found cache entry. [Current time (05/15/2023 19:00:39) - Expiration Time (05/15/2023 19:06:33 +00:00) - Extended Expiration Time (05/15/2023 19:06:33 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374]      
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-05-15 19:00:39Z - eb098419-7727-4576-b567-99b8e1a41374]  AT expiration time: 15/05/2023 19:06:33 +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-05-15T19:06:33.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'tenantGUID', UserId: 'xxxx@xxxxx.co.uk'   
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/tenantGUID/resourceGroups/resourceGroupName/providers/Microsoft.Web/sites/resourceName/config/web?api-version=2021-01-15

Headers:
x-ms-client-request-id        : 354ef4c5-923d-4ab0-9f90-1c949ee2aaa7
Accept-Language               : en-US

Body:
{
  "properties": {
    "numberOfWorkers": 1,
    "defaultDocuments": [
      "Default.htm",
      "Default.html",
      "Default.asp",
      "index.htm",
      "index.html",
      "iisstart.htm",
      "default.aspx",
      "index.php",
      "hostingstart.html"
    ],
    "netFrameworkVersion": "v4.0",
    "phpVersion": "5.6",
    "pythonVersion": "",
    "nodeVersion": "",
    "linuxFxVersion": "",
    "requestTracingEnabled": false,
    "remoteDebuggingEnabled": false,
    "remoteDebuggingVersion": "VS2019",
    "httpLoggingEnabled": false,
    "logsDirectorySizeLimit": 35,
    "detailedErrorLoggingEnabled": false,
    "publishingUsername": "$resourceName",
    "appSettings": [
      {
        "name": "SnapshotDebugger_EXTENSION_VERSION",
        "value": "~1"
      },
      {
        "name": "XDT_MicrosoftApplicationInsights_BaseExtensions",
        "value": "~1"
      },
      {
        "name": "ApplicationInsightsAgent_EXTENSION_VERSION",
        "value": "~2"
      },
      {
        "name": "APPINSIGHTS_PROFILERFEATURE_VERSION",
        "value": "1.0.0"
      },
      {
        "name": "XDT_MicrosoftApplicationInsights_Mode",
        "value": "recommended"
      },
      {
        "name": "DiagnosticServices_EXTENSION_VERSION",
        "value": "~3"
      },
      {
        "name": "APPINSIGHTS_SNAPSHOTFEATURE_VERSION",
        "value": "1.0.0"
      },
      {
        "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
        "value": "e64d6ab6-64be-4d9f-a171-a52af788d56b"
      },
      {
        "name": "InstrumentationEngine_EXTENSION_VERSION",
        "value": "~1"
      },
      {
        "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
        "value": "InstrumentationKey=e64d6ab6-64be-4d9f-a171-a52af788d56b"
      },
      {
        "name": "WEBSITE_VNET_ROUTE_ALL",
        "value": "1"
      },
      {
        "name": "WEBSITE_DNS_SERVER",
        "value": "168.63.129.16"
      }
    ],
    "connectionStrings": [],
    "scmType": "VSTSRM",
    "use32BitWorkerProcess": true,
    "webSocketsEnabled": false,
    "alwaysOn": true,
    "appCommandLine": "",
    "managedPipelineMode": "Integrated",
    "virtualApplications": [
      {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": true
      }
    ],
    "loadBalancing": "LeastRequests",
    "experiments": {
      "rampUpRules": []
    },
    "autoHealEnabled": false,
    "vnetName": "11c92d10-029e-49d1-a65a-5bf90f610979_Web",
    "vnetRouteAllEnabled": false,
    "cors": {
      "allowedOrigins": [],
      "supportCredentials": false
    },
    "localMySqlEnabled": false,
    "managedServiceIdentityId": 30280,
    "ipSecurityRestrictions": [
      {
        "ipAddress": "Any",
        "action": "Allow",
        "priority": 2147483647,
        "name": "Allow all",
        "description": "Allow all access"
      }
    ],
    "scmIpSecurityRestrictions": [
      {
        "ipAddress": "Any",
        "action": "Allow",
        "priority": 2147483647,
        "name": "Allow all",
        "description": "Allow all access"
      }
    ],
    "scmIpSecurityRestrictionsUseMain": false,
    "http20Enabled": true,
    "minTlsVersion": "1.2",
    "ftpsState": "Disabled"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
ETag                          : "1D9875F6D67416B"
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : ee71c565-4ac3-475e-b8a2-5684054c82b2
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : cee2706a-3f5f-4321-8208-d9ae0cbcf35e
x-ms-routing-request-id       : UKSOUTH:20230515T190040Z:cee2706a-3f5f-4321-8208-d9ae0cbcf35e
X-Content-Type-Options        : nosniff
Date                          : Mon, 15 May 2023 19:00:40 GMT

Body:
{
  "id": "/subscriptions/tenantGUID/resourceGroups/resourceGroupName/providers/Microsoft.Web/sites/resourceName",
  "name": "resourceName",
  "type": "Microsoft.Web/sites",
  "location": "West Europe",
  "properties": {
    "numberOfWorkers": 1,
    "defaultDocuments": [
      "Default.htm",
      "Default.html",
      "Default.asp",
      "index.htm",
      "index.html",
      "iisstart.htm",
      "default.aspx",
      "index.php",
      "hostingstart.html"
    ],
    "netFrameworkVersion": "v4.0",
    "phpVersion": "5.6",
    "pythonVersion": "",
    "nodeVersion": "",
    "powerShellVersion": "",
    "linuxFxVersion": "",
    "windowsFxVersion": null,
    "windowsConfiguredStacks": [],
    "requestTracingEnabled": false,
    "remoteDebuggingEnabled": false,
    "remoteDebuggingVersion": "VS2019",
    "httpLoggingEnabled": false,
    "azureMonitorLogCategories": [
      "AppServiceAntivirusScanAuditLogs",
      "AppServiceHTTPLogs",
      "AppServiceConsoleLogs",
      "AppServiceAppLogs",
      "AppServiceFileAuditLogs",
      "AppServiceAuditLogs",
      "AppServiceIPSecAuditLogs",
      "AppServicePlatformLogs"
    ],
    "acrUseManagedIdentityCreds": false,
    "acrUserManagedIdentityID": null,
    "logsDirectorySizeLimit": 35,
    "detailedErrorLoggingEnabled": false,
    "publishingUsername": "$resourceName",
    "publishingPassword": null,
    "appSettings": null,
    "metadata": null,
    "connectionStrings": null,
    "machineKey": null,
    "handlerMappings": null,
    "documentRoot": null,
    "scmType": "VSTSRM",
    "use32BitWorkerProcess": true,
    "webSocketsEnabled": false,
    "alwaysOn": true,
    "javaVersion": null,
    "javaContainer": null,
    "javaContainerVersion": null,
    "appCommandLine": "",
    "managedPipelineMode": "Integrated",
    "virtualApplications": [
      {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": true,
        "virtualDirectories": null
      }
    ],
    "winAuthAdminState": 0,
    "winAuthTenantState": 0,
    "customAppPoolIdentityAdminState": false,
    "customAppPoolIdentityTenantState": false,
    "runtimeADUser": null,
    "runtimeADUserPassword": null,
    "loadBalancing": "LeastRequests",
    "routingRules": [],
    "experiments": {
      "rampUpRules": []
    },
    "limits": null,
    "autoHealEnabled": false,
    "autoHealRules": null,
    "tracingOptions": null,
    "vnetName": "11c92d10-029e-49d1-a65a-5bf90f610979_Web",
    "vnetRouteAllEnabled": false,
    "vnetPrivatePortsCount": 0,
    "publicNetworkAccess": null,
    "siteAuthEnabled": false,
    "siteAuthSettings": {
      "enabled": null,
      "unauthenticatedClientAction": null,
      "tokenStoreEnabled": null,
      "allowedExternalRedirectUrls": null,
      "defaultProvider": null,
      "clientId": null,
      "clientSecret": null,
      "clientSecretSettingName": null,
      "clientSecretCertificateThumbprint": null,
      "issuer": null,
      "allowedAudiences": null,
      "additionalLoginParams": null,
      "isAadAutoProvisioned": false,
      "aadClaimsAuthorization": null,
      "googleClientId": null,
      "googleClientSecret": null,
      "googleClientSecretSettingName": null,
      "googleOAuthScopes": null,
      "facebookAppId": null,
      "facebookAppSecret": null,
      "facebookAppSecretSettingName": null,
      "facebookOAuthScopes": null,
      "gitHubClientId": null,
      "gitHubClientSecret": null,
      "gitHubClientSecretSettingName": null,
      "gitHubOAuthScopes": null,
      "twitterConsumerKey": null,
      "twitterConsumerSecret": null,
      "twitterConsumerSecretSettingName": null,
      "microsoftAccountClientId": null,
      "microsoftAccountClientSecret": null,
      "microsoftAccountClientSecretSettingName": null,
      "microsoftAccountOAuthScopes": null,
      "configVersion": null
    },
    "cors": {
      "allowedOrigins": [],
      "supportCredentials": false
    },
    "push": null,
    "apiDefinition": null,
    "apiManagementConfig": null,
    "autoSwapSlotName": null,
    "localMySqlEnabled": false,
    "managedServiceIdentityId": 30280,
    "xManagedServiceIdentityId": null,
    "keyVaultReferenceIdentity": null,
    "ipSecurityRestrictions": [
      {
        "ipAddress": "Any",
        "action": "Allow",
        "priority": 2147483647,
        "name": "Allow all",
        "description": "Allow all access"
      }
    ],
    "ipSecurityRestrictionsDefaultAction": null,
    "scmIpSecurityRestrictions": [
      {
        "ipAddress": "Any",
        "action": "Allow",
        "priority": 2147483647,
        "name": "Allow all",
        "description": "Allow all access"
      }
    ],
    "scmIpSecurityRestrictionsDefaultAction": null,
    "scmIpSecurityRestrictionsUseMain": false,
    "http20Enabled": true,
    "minTlsVersion": "1.2",
    "minTlsCipherSuite": null,
    "supportedTlsCipherSuites": null,
    "scmMinTlsVersion": "1.2",
    "ftpsState": "Disabled",
    "preWarmedInstanceCount": 0,
    "functionAppScaleLimit": null,
    "elasticWebAppScaleLimit": 0,
    "healthCheckPath": null,
    "fileChangeAuditEnabled": true,
    "functionsRuntimeScaleMonitoringEnabled": false,
    "websiteTimeZone": null,
    "minimumElasticInstanceCount": 0,
    "azureStorageAccounts": {},
    "http20ProxyFlag": 0,
    "sitePort": null,
    "antivirusScanEnabled": true,
    "storageType": "StorageVolume"
  }
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/tenantGUID/resourceGroups/resourceGroupName/providers/Microsoft.Web/sites/resourceName/config/appsettings?api-version=2021-01-15

Headers:
x-ms-client-request-id        : 354ef4c5-923d-4ab0-9f90-1c949ee2aaa7
Accept-Language               : en-US

Body:
{
  "properties": {
    "SnapshotDebugger_EXTENSION_VERSION": "~1",
    "XDT_MicrosoftApplicationInsights_BaseExtensions": "~1",
    "ApplicationInsightsAgent_EXTENSION_VERSION": "~2",
    "APPINSIGHTS_PROFILERFEATURE_VERSION": "1.0.0",
    "XDT_MicrosoftApplicationInsights_Mode": "recommended",
    "DiagnosticServices_EXTENSION_VERSION": "~3",
    "APPINSIGHTS_SNAPSHOTFEATURE_VERSION": "1.0.0",
    "APPINSIGHTS_INSTRUMENTATIONKEY": "e64d6ab6-64be-4d9f-a171-a52af788d56b",
    "InstrumentationEngine_EXTENSION_VERSION": "~1",
    "APPLICATIONINSIGHTS_CONNECTION_STRING": "InstrumentationKey=e64d6ab6-64be-4d9f-a171-a52af788d56b",
    "WEBSITE_VNET_ROUTE_ALL": "1",
    "WEBSITE_DNS_SERVER": "168.63.129.16"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
ETag                          : "1D9875F8AD1FA00"
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 019ecd1b-aba3-4e07-ac68-04160da6208b
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-correlation-request-id   : 53546f40-5a06-4acc-96d2-7c923a856cd6
x-ms-routing-request-id       : UKSOUTH:20230515T190041Z:53546f40-5a06-4acc-96d2-7c923a856cd6
X-Content-Type-Options        : nosniff
Date                          : Mon, 15 May 2023 19:00:41 GMT

Body:
{
  "id": "/subscriptions/tenantGUID/resourceGroups/resourceGroupName/providers/Microsoft.Web/sites/resourceName/config/appsettings",
  "name": "appsettings",
  "type": "Microsoft.Web/sites/config",
  "location": "West Europe",
  "properties": {
    "SnapshotDebugger_EXTENSION_VERSION": "~1",
    "XDT_MicrosoftApplicationInsights_BaseExtensions": "~1",
    "ApplicationInsightsAgent_EXTENSION_VERSION": "~2",
    "APPINSIGHTS_PROFILERFEATURE_VERSION": "1.0.0",
    "XDT_MicrosoftApplicationInsights_Mode": "recommended",
    "DiagnosticServices_EXTENSION_VERSION": "~3",
    "APPINSIGHTS_SNAPSHOTFEATURE_VERSION": "1.0.0",
    "APPINSIGHTS_INSTRUMENTATIONKEY": "e64d6ab6-64be-4d9f-a171-a52af788d56b",
    "InstrumentationEngine_EXTENSION_VERSION": "~1",
    "APPLICATIONINSIGHTS_CONNECTION_STRING": "InstrumentationKey=e64d6ab6-64be-4d9f-a171-a52af788d56b",
    "WEBSITE_VNET_ROUTE_ALL": "1",
    "WEBSITE_DNS_SERVER": "168.63.129.16"
  }
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/tenantGUID/resourceGroups/resourceGroupName/providers/Microsoft.Web/sites/resourceName/config/connectionstrings?api-version=2021-01-15

Headers:
x-ms-client-request-id        : 354ef4c5-923d-4ab0-9f90-1c949ee2aaa7
Accept-Language               : en-US

Body:
{
  "properties": {}
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
ETag                          : "1D9875F8BEBC16B"
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 51ac73c5-7dcd-4801-a4f8-796fca842dab
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-writes: 1197
x-ms-correlation-request-id   : b402e8ad-c17a-4b4d-a8ad-05dc73e8bd35
x-ms-routing-request-id       : UKSOUTH:20230515T190042Z:b402e8ad-c17a-4b4d-a8ad-05dc73e8bd35
X-Content-Type-Options        : nosniff
Date                          : Mon, 15 May 2023 19:00:42 GMT

Body:
{
  "id": "/subscriptions/tenantGUID/resourceGroups/resourceGroupName/providers/Microsoft.Web/sites/resourceName/config/connectionstrings",
  "name": "connectionstrings",
  "type": "Microsoft.Web/sites/config",
  "location": "West Europe",
  "properties": {}
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/tenantGUID/resourceGroups/resourceGroupName/providers/Microsoft.Web/sites/resourceName?api-version=2021-01-15

Headers:
x-ms-client-request-id        : 354ef4c5-923d-4ab0-9f90-1c949ee2aaa7
Accept-Language               : en-US

Body:
{
  "VnetInfo": [
    {
      "properties": {
        "vnetResourceId": "/subscriptions/tenantGUID/resourceGroups/tdi-gen-dev1/providers/Microsoft.Network/virtualNetworks/tdi-vnet-dev1/subnets/Web",
        "isSwift": true
      }
    }
  ],
  "properties": {
    "enabled": true,
    "hostNameSslStates": [
      {
        "name": "resourceName.azurewebsites.net",
        "sslState": "Disabled",
        "hostType": "Standard"
      },
      {
        "name": "resourceName.scm.azurewebsites.net",
        "sslState": "Disabled",
        "hostType": "Repository"
      }
    ],
    "serverFarmId": "/subscriptions/tenantGUID/resourceGroups/resourceGroupName/providers/Microsoft.Web/serverfarms/aspName",
    "reserved": false,
    "isXenon": false,
    "siteConfig": {
      "numberOfWorkers": 1,
      "defaultDocuments": [
        "Default.htm",
        "Default.html",
        "Default.asp",
        "index.htm",
        "index.html",
        "iisstart.htm",
        "default.aspx",
        "index.php",
        "hostingstart.html"
      ],
      "netFrameworkVersion": "v4.0",
      "phpVersion": "5.6",
      "pythonVersion": "",
      "nodeVersion": "",
      "linuxFxVersion": "",
      "requestTracingEnabled": false,
      "remoteDebuggingEnabled": false,
      "remoteDebuggingVersion": "VS2019",
      "httpLoggingEnabled": false,
      "logsDirectorySizeLimit": 35,
      "detailedErrorLoggingEnabled": false,
      "publishingUsername": "$resourceName",
      "appSettings": [
        {
          "name": "SnapshotDebugger_EXTENSION_VERSION",
          "value": "~1"
        },
        {
          "name": "XDT_MicrosoftApplicationInsights_BaseExtensions",
          "value": "~1"
        },
        {
          "name": "ApplicationInsightsAgent_EXTENSION_VERSION",
          "value": "~2"
        },
        {
          "name": "APPINSIGHTS_PROFILERFEATURE_VERSION",
          "value": "1.0.0"
        },
        {
          "name": "XDT_MicrosoftApplicationInsights_Mode",
          "value": "recommended"
        },
        {
          "name": "DiagnosticServices_EXTENSION_VERSION",
          "value": "~3"
        },
        {
          "name": "APPINSIGHTS_SNAPSHOTFEATURE_VERSION",
          "value": "1.0.0"
        },
        {
          "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
          "value": "e64d6ab6-64be-4d9f-a171-a52af788d56b"
        },
        {
          "name": "InstrumentationEngine_EXTENSION_VERSION",
          "value": "~1"
        },
        {
          "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
          "value": "InstrumentationKey=e64d6ab6-64be-4d9f-a171-a52af788d56b"
        },
        {
          "name": "WEBSITE_VNET_ROUTE_ALL",
          "value": "1"
        },
        {
          "name": "WEBSITE_DNS_SERVER",
          "value": "168.63.129.16"
        }
      ],
      "connectionStrings": [],
      "scmType": "VSTSRM",
      "use32BitWorkerProcess": true,
      "webSocketsEnabled": false,
      "alwaysOn": true,
      "appCommandLine": "",
      "managedPipelineMode": "Integrated",
      "virtualApplications": [
        {
          "virtualPath": "/",
          "physicalPath": "site\\wwwroot",
          "preloadEnabled": true
        }
      ],
      "loadBalancing": "LeastRequests",
      "experiments": {
        "rampUpRules": []
      },
      "autoHealEnabled": false,
      "vnetName": "11c92d10-029e-49d1-a65a-5bf90f610979_Web",
      "vnetRouteAllEnabled": false,
      "cors": {
        "allowedOrigins": [],
        "supportCredentials": false
      },
      "localMySqlEnabled": false,
      "managedServiceIdentityId": 30280,
      "ipSecurityRestrictions": [
        {
          "ipAddress": "Any",
          "action": "Allow",
          "priority": 2147483647,
          "name": "Allow all",
          "description": "Allow all access"
        }
      ],
      "scmIpSecurityRestrictions": [
        {
          "ipAddress": "Any",
          "action": "Allow",
          "priority": 2147483647,
          "name": "Allow all",
          "description": "Allow all access"
        }
      ],
      "scmIpSecurityRestrictionsUseMain": false,
      "http20Enabled": true,
      "minTlsVersion": "1.2",
      "ftpsState": "Disabled"
    },
    "scmSiteAlsoStopped": false,
    "clientAffinityEnabled": true,
    "clientCertEnabled": false,
    "hostNamesDisabled": false,
    "customDomainVerificationId": "F6E84F638B6A8CE5F642CBD6A390EE232AF221717ECCA3B27493A4FF39AE3533",
    "containerSize": 0,
    "dailyMemoryTimeQuota": 0,
    "httpsOnly": true,
    "virtualNetworkSubnetId": "/subscriptions/tenantGUID/resourceGroups/tdi-gen-dev1/providers/Microsoft.Network/virtualNetworks/tdi-vnet-dev1/subnets/Web"
  },
  "identity": {
    "type": "SystemAssigned"
  },
  "kind": "app",
  "location": "West Europe"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 1bb11fa4-c88e-4d56-bbb8-505ca3fee553
x-ms-correlation-request-id   : 1bb11fa4-c88e-4d56-bbb8-505ca3fee553
x-ms-routing-request-id       : UKSOUTH:20230515T190042Z:1bb11fa4-c88e-4d56-bbb8-505ca3fee553
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Mon, 15 May 2023 19:00:42 GMT

Body:
{
  "error": {
    "code": "InvalidRequestContent",
    "message": "The request content was invalid and could not be deserialized: 'Could not find member 'VnetInfo' on object of type 'ResourceDefinition'. Path 'VnetInfo', line 2, position 15.'."
  }
}


DEBUG: 20:00:43 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Set-AzWebApp: Operation returned an invalid status code 'BadRequest'
DEBUG: 20:00:43 - [ConfigManager] Got [False] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
DEBUG: 20:00:43 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Websites:2.15.1; CommandName: Set-AzWebApp; PSVersion: 7.2.11; IsSuccess: False; Duration: 00:00:04.1501414; Exception: Operation returned an invalid status code 'BadRequest';
DEBUG: 20:00:43 - SetAzureWebAppCmdlet end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.11
PSEdition                      Core
GitCommitId                    7.2.11
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Directory: C:\Users\paul.KBTECH\OneDrive - KB Tech Ltd\Documents 1\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.12.2                Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCo
Script     5.4.0                 Az.Aks                              Core,Desk {Get-AzAksCluster, New-AzAksCluster, Remove-AzAksCluster, Import-AzAk
Script     4.9.3                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyV
Script     5.7.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplication
Script     6.6.1                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignme
Script     2.15.1                Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Re

    Directory: C:\Program Files\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     9.6.0                 Az                                  Core,Desk
Script     2.0.0                 Az.Advisor                          Core,Desk {Disable-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Get
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, G
Script     4.0.2                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Ad
Script     1.2.0                 Az.AppConfiguration                 Core,Desk {Get-AzAppConfigurationStore, Get-AzAppConfigurationStoreKey, New-AzA
Script     2.2.2                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzAp
Script     2.0.0                 Az.Attestation                      Core,Desk {Get-AzAttestationPolicy, Set-AzAttestationPolicy, Reset-AzAttestatio
Script     1.0.0                 Az.Automanage                       Core,Desk {Get-AzAutomanageBestPractice, Get-AzAutomanageConfigProfile, Get-AzA
Script     1.9.1                 Az.Automation                       Core,Desk {Set-AzAutomationPython3Package, New-AzAutomationPython3Package, Remo
Script     3.4.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, Ne
Script     2.0.1                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, 
Script     2.1.0                 Az.Cdn                              Core,Desk {Clear-AzCdnEndpointContent, Clear-AzFrontDoorCdnEndpointContent, Dis
Script     1.2.0                 Az.CloudService                     Core,Desk {Get-AzCloudService, Get-AzCloudServiceInstanceView, Get-AzCloudServi
Script     1.13.1                Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, G
Script     1.0.0                 Az.ConfidentialLedger               Core,Desk {Get-AzConfidentialLedger, New-AzConfidentialLedger, New-AzConfidenti
Script     3.2.0                 Az.ContainerInstance                Core,Desk {Add-AzContainerInstanceOutput, Get-AzContainerGroup, Get-AzContainer
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeD
Script     1.5.0                 Az.Databricks                       Core,Desk {Get-AzDatabricksAccessConnector, Get-AzDatabricksOutboundNetworkDepe
Script     1.16.13               Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Re
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCre
Script     1.3.0                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedI
Script     1.2.0                 Az.DataProtection                   Core,Desk {Backup-AzDataProtectionBackupInstanceAdhoc, Edit-AzDataProtectionPol
Script     1.0.1                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataShareAccount, Remove-AzDataShareAc
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifa
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDt
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Se
Script     1.6.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, Ne
Script     3.2.3                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubName
Script     1.10.0                Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoo
Script     4.0.6                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctio
Script     5.0.1                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsi
Script     2.0.0                 Az.HealthcareApis                   Core,Desk {Get-AzHealthcareApisService, Get-AzHealthcareApisWorkspace, Get-AzHe
Script     2.7.5                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConn
Script     2.2.0                 Az.Kusto                            Core,Desk {Add-AzKustoClusterLanguageExtension, Add-AzKustoDatabasePrincipal, G
Script     1.5.0                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly,
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-A
Script     1.2.1                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceC
Script     1.1.1                 Az.ManagedServiceIdentity           Core,Desk {Get-AzFederatedIdentityCredentials, Get-AzSystemAssignedIdentity, Ge
Script     3.0.0                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, Get-AzManagedServicesDefinition, Ge
Script     2.0.0                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Invoke-AzMarketplaceSignTerms, Set-AzMarketp
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaSer
Script     2.1.0                 Az.Migrate                          Core,Desk {Get-AzMigrateDiscoveredServer, Get-AzMigrateJob, Get-AzMigrateProjec
Script     4.4.1                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLog
Script     1.1.0                 Az.MySql                            Core,Desk {Get-AzMySqlConfiguration, Get-AzMySqlConnectionString, Get-AzMySqlFi
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-A
Script     3.2.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperation
Script     1.1.0                 Az.PostgreSql                       Core,Desk {Get-AzPostgreSqlConfiguration, Get-AzPostgreSqlConnectionString, Get
Script     1.0.3                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone,
Script     1.7.1                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get
Script     1.1.0                 Az.RedisEnterpriseCache             Core,Desk {Export-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCache, Get-AzRed
Script     1.0.4                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Re
Script     1.1.0                 Az.ResourceMover                    Core,Desk {Add-AzResourceMoverMoveResource, Get-AzResourceMoverMoveCollection, 
Script     1.4.0                 Az.Security                         Core,Desk {Get-AzSecuritySolution, Get-AzSecuritySolutionsReferenceData, New-Az
Script     3.0.1                 Az.SecurityInsights                 Core,Desk {Get-AzSentinelAlertRule, Get-AzSentinelAlertRuleAction, Get-AzSentin
Script     2.2.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceB
Script     3.1.1                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricNode, Add-A
Script     1.5.0                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     1.1.1                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM…}
Script     1.4.3                 Az.StackHCI                         Core,Desk {Add-AzStackHCIVMAttestation, Disable-AzStackHCIAttestation, Disable-
Script     1.0.0                 Az.StorageMover                     Core,Desk {Get-AzStorageMover, Get-AzStorageMoverAgent, Get-AzStorageMoverEndpo
Script     1.7.0                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Ge
Script     2.0.0                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyticsClusterStreamingJ
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportProblemClassification, Get-AzSupp
Script     1.2.0                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerC

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     5.3.1                 Azure                               Desk      {Get-AzureAutomationCertificate, Get-AzureAutomationConnection, New-A
Script     5.1.2                 Azure                               Desk      {Get-AzureAutomationCertificate, Get-AzureAutomationConnection, New-A
Manifest   0.5.0                 Azure.AnalysisServices              Desk      {Add-AzureAnalysisServicesAccount, Restart-AzureAnalysisServicesInsta
Script     4.6.1                 Azure.Storage                       Desk      {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-AzureStora
Script     4.2.1                 Azure.Storage                       Desk      {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-AzureStora
Binary     2.0.2.140             AzureAD                             Desk
Script     5.7.0                 AzureRM                             Desk
Script     0.6.6                 AzureRM.AnalysisServices            Desk      {Resume-AzureRmAnalysisServicesServer, Suspend-AzureRmAnalysisService
Script     5.1.2                 AzureRM.ApiManagement               Desk      {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementSsoToken, Ne
Script     0.1.3                 AzureRM.ApplicationInsights         Desk      {Get-AzureRmApplicationInsights, New-AzureRmApplicationInsights, Remo
Script     4.3.2                 AzureRM.Automation                  Desk      {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomationJobOutp
Script     4.0.4                 AzureRM.Backup                      Desk      {Backup-AzureRmBackupItem, Enable-AzureRmBackupContainerReregistratio
Script     4.0.6                 AzureRM.Batch                       Desk      {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-AzureRmBatc
Script     0.14.1                AzureRM.Billing                     Desk      {Get-AzureRmBillingInvoice, Get-AzureRmBillingPeriod, Get-AzureRmEnro
Script     4.2.2                 AzureRM.Cdn                         Desk      {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSsoUrl, New-AzureRmCdnPr
Script     0.9.4                 AzureRM.CognitiveServices           Desk      {Get-AzureRmCognitiveServicesAccount, Get-AzureRmCognitiveServicesAcc
Script     4.6.0                 AzureRM.Compute                     Desk      {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, New-Azure
Script     0.3.1                 AzureRM.Consumption                 Desk      Get-AzureRmConsumptionUsageDetail
Script     0.2.5                 AzureRM.ContainerInstance           Desk      {New-AzureRmContainerGroup, Get-AzureRmContainerGroup, Remove-AzureRm
Script     1.0.4                 AzureRM.ContainerRegistry           Desk      {New-AzureRmContainerRegistry, Get-AzureRmContainerRegistry, Update-A
Script     4.2.2                 AzureRM.DataFactories               Desk      {Remove-AzureRmDataFactory, Get-AzureRmDataFactoryRun, Get-AzureRmDat
Script     0.5.3                 AzureRM.DataFactoryV2               Desk      {Set-AzureRmDataFactoryV2, Update-AzureRmDataFactoryV2, Get-AzureRmDa
Script     4.2.3                 AzureRM.DataLakeAnalytics           Desk      {Get-AzureRmDataLakeAnalyticsDataSource, New-AzureRmDataLakeAnalytics
Script     5.2.0                 AzureRM.DataLakeStore               Desk      {Get-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDataLakeSto
Script     4.0.4                 AzureRM.DevTestLabs                 Desk      {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShutdownPolicy
Script     4.1.2                 AzureRM.Dns                         Desk      {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remove-AzureRmD
Script     0.3.2                 AzureRM.EventGrid                   Desk      {New-AzureRmEventGridTopic, Get-AzureRmEventGridTopic, Set-AzureRmEve
Script     0.6.3                 AzureRM.EventHub                    Desk      {New-AzureRmEventHubNamespace, Get-AzureRmEventHubNamespace, Set-Azur
Script     4.1.2                 AzureRM.HDInsight                   Desk      {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSqoopJobDefinition, Wai
Script     4.0.4                 AzureRM.Insights                    Desk      {Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-AzureRmLogPro
Script     3.1.2                 AzureRM.IotHub                      Desk      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHubConsumerGroup, Get-Az
Script     4.3.0                 AzureRM.KeyVault                    Desk      {Add-AzureKeyVaultCertificate, Set-AzureKeyVaultCertificateAttribute,
Script     4.0.3                 AzureRM.LogicApp                    Desk      {Get-AzureRmIntegrationAccountAgreement, Get-AzureRmIntegrationAccoun
Script     0.17.2                AzureRM.MachineLearning             Desk      {Move-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitmentAssociat
Script     0.4.2                 AzureRM.MachineLearningCompute      Desk      {Get-AzureRmMlOpCluster, Get-AzureRmMlOpClusterKey, Test-AzureRmMlOpC
Script     0.2.1                 AzureRM.MarketplaceOrdering         Desk      {Get-AzureRmMarketplaceTerms, Set-AzureRmMarketplaceTerms}
Script     0.9.2                 AzureRM.Media                       Desk      {Sync-AzureRmMediaServiceStorageKeys, Set-AzureRmMediaServiceKey, Get
Script     5.5.2                 AzureRM.Resources                   Desk      {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, Get-AzureRmRoleAssignment, New-AzureRmRoleAssignment…}
Script     0.16.3                AzureRM.Scheduler                   Desk      {Disable-AzureRmSchedulerJobCollection, Enable-AzureRmSchedulerJobCollection, Get-AzureRmSchedulerJobCollection, Get-AzureRmSchedulerJob…}
Script     4.1.2                 AzureRM.ServerManagement            Desk      {Invoke-AzureRmServerManagementPowerShellCommand, Get-AzureRmServerManagementSession, New-AzureRmServerManagementSession, Remove-AzureRmServerManagementSess…
Script     0.6.4                 AzureRM.ServiceBus                  Desk      {New-AzureRmServiceBusNamespace, Get-AzureRmServiceBusNamespace, Set-AzureRmServiceBusNamespace, Remove-AzureRmServiceBusNamespace…}
Script     0.3.4                 AzureRM.ServiceFabric               Desk      {Add-AzureRmServiceFabricApplicationCertificate, Add-AzureRmServiceFabricClientCertificate, Add-AzureRmServiceFabricClusterCertificate, Add-AzureRmServiceFa…
Script     5.0.6                 AzureRM.SiteRecovery                Desk      {Get-AzureRmSiteRecoveryFabric, New-AzureRmSiteRecoveryFabric, Remove-AzureRmSiteRecoveryFabric, Stop-AzureRmSiteRecoveryJob…}
Script     4.4.0                 AzureRM.Sql                         Desk      {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-AzureRmSqlDatabaseTransparentDataEncryptionActivity, Set-AzureRmSqlDatabaseTransparentDataEncryption, …
Script     4.2.3                 AzureRM.Storage                     Desk      {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New-AzureRmStorageAccount, New-AzureRmStorageAccountKey…}
Script     4.0.4                 AzureRM.StreamAnalytics             Desk      {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnalyticsDefaultFunctionDefinition, New-AzureRmStreamAnalyticsFunction, Remove-AzureRmStreamAnalyticsF…
Script     4.0.1                 AzureRM.Tags                        Desk      {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}
Script     4.0.3                 AzureRM.TrafficManager              Desk      {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTrafficManagerEndpoint, Set-AzureRmTrafficManagerEndpoint, Get-AzureRmTrafficManagerEndpoint…}
Script     4.0.2                 AzureRM.UsageAggregates             Desk      Get-UsageAggregates
Script     4.2.2                 AzureRM.Websites                    Desk      {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New-AzureRmAppServicePlan, Remove-AzureRmAppServicePlan…}
```

### Error output

```PowerShell
Resolve-AzError
DEBUG: 19:04:34 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 19:04:34 - using account id 'xxxx@xxxxx.co.uk'...
DEBUG: 19:04:34 - [ConfigManager] Got [False] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].

   HistoryId: 3

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.WebSites.WebAppsOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String name, Site siteEnvelope, Dictionary`2 customHeaders, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.Management.WebSites.WebAppsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String name, Site siteEnvelope, Dictionary`2 customHeaders, CancellationToken cancellationToken)  
                    at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.CreateOrUpdateAsync(IWebAppsOperations operations, String resourceGroupName, String name, Site siteEnvelope, CancellationToken cancellationToken)     
                    at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.CreateOrUpdate(IWebAppsOperations operations, String resourceGroupName, String name, Site siteEnvelope)
                    at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.UpdateWebApp(String resourceGroupName, String location, String webAppName, String slotName, String appServicePlan, Site siteEnvelope, String
                 appServicePlanRg)
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponseException
InvocationInfo : {Set-AzWebApp}
Line           : $web = $web | Set-AzWebApp -Debug
Position       : At line:1 char:15
                 + $web = $web | Set-AzWebApp -Debug
                 +               ~~~~~~~~~~~~~~~~~~~
HistoryId      : 3



DEBUG: 19:04:34 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.12.2; CommandName: Resolve-AzError; PSVersion: 7.2.11; IsSuccess: True; Duration: 00:00:00.0163718
DEBUG: 19:04:34 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: 19:04:34 - ResolveError end processing.
```

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
#21820 

I have an issue when trying to update a app service using Set-AzWebApp with an object retrieved using Get-AzWebApp, at first i thought i was causing the issue with my changes that happen between calling get-azwebapp and set-azwebapp, but even if i make no changes it still errors. This used to work. I also tried updating to latest az modules but that made no difference, so I'm guessing the issue is in the api end.

If i run this simple 2 lines of code it errors with a badrequest

$web = Get-AzWebApp -ResourceGroupName -Name -ErrorAction SilentlyContinue
$web = $web | Set-AzWebApp
## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

File: src/Websites/Websites/Utilities/WebsitesClient.cs [hunk 1]
```diff
@@ -112,6 +112,9 @@ public void UpdateWebApp(string resourceGroupName, string location, string webAp
 
             if (siteEnvelope != null)
             {
+                System.Reflection.PropertyInfo property = siteEnvelope.GetType().GetProperty("VnetInfo");
```
Comment (vidai-msft) [inline src/Websites/Websites/Utilities/WebsitesClient.cs:115]: Is your purpose to find a specific sub-object of class Site which has VnetInfo property or all sub-objects which have this property?

Comment (Kotasudhakarreddy) [reply src/Websites/Websites/Utilities/WebsitesClient.cs:115]: Actually, the VnetInfo property is not part of the Site class. It has been added to wrapper class [PSSite ](https://github.com/Azure/azure-powershell/blob/main/src/Websites/Websites/Models.WebApp/PSSite.cs#L93)to fetch VnetInfo for the webapp. When the PSSite object is used to update the webapp, it throws the deserialization exception as it expects an object of type Site and it does not have a VnetInfo property. So I am checking the existence of VnetInfo and making it null before deserializing.

Comment (vidai-msft) [reply src/Websites/Websites/Utilities/WebsitesClient.cs:115]: PSSite is a child class of Site. If in the future, another child class which also has the VnetInfo property, would this piece of code have problem? So my point is would you check if siteEnvelop is an instance of PSSite, and then you can access the VnetInfo directly after converting the siteEnvelop object to an instance of PSSite? Or if any siteEnvelop instance which has that property, you would set its value as null.

Comment (Kotasudhakarreddy) [reply src/Websites/Websites/Utilities/WebsitesClient.cs]: updated the code as per the review comments.

File: src/Websites/Websites/Utilities/WebsitesClient.cs [hunk 2]
```diff
@@ -112,9 +112,11 @@ public void UpdateWebApp(string resourceGroupName, string location, string webAp
 
             if (siteEnvelope != null)
             {
-                System.Reflection.PropertyInfo property = siteEnvelope.GetType().GetProperty("VnetInfo");
-                if (property != null)
-                    property.SetValue(siteEnvelope, null);
+                if (siteEnvelope is PSSite)
+                {
+                    PSSite site = siteEnvelope as PSSite;
```
Comment (vidai-msft) [inline src/Websites/Websites/Utilities/WebsitesClient.cs:117]: No need to use `as` operator here since the siteEnvelope is for sure an instance of PSSite
`((PSSite)siteEnvelope).VnetInfo = null;` works.

Comment (Kotasudhakarreddy) [reply src/Websites/Websites/Utilities/WebsitesClient.cs]: Done!

**Review by vidai-msft — APPROVED** [review]
