### PR TITLE
[AppService]: fix #19592- 'Import-AzWebAppKeyVaultCertificate' 'Object reference' error when importing a certificate previously imported via Azure Portal 

### LINKED ISSUE #19592: 'Import-AzWebAppKeyVaultCertificate' 'Object reference' error when importing a certificate previously imported via Azure Portal
## Steps to Replicate
1. Follow the steps in [Import a certificate from your vault to your app](https://learn.microsoft.com/en-us/azure/app-service/configure-ssl-certificate?tabs=apex%2Cportal#import-a-certificate-from-your-vault-to-your-app).
2. In the network trace I can see the following properties:
    - **URL:** https://management.azure.com/subscriptions/#redacted#/resourceGroups/perf-test-ause/providers/Microsoft.Web/certificates/test1-keyvault-34-grewgrewrewhr?api-version=2018-11-01
    - **payload:**
       ```Json
      {
          "location": "Australia Southeast",
          "properties": {
              "ServerFarmId": "/subscriptions/#redacted#/resourceGroups/perf-test-ause/providers/Microsoft.Web/serverfarms/ASP-perftestause-a9d0",
              "keyVaultId": "/subscriptions/#redacted#/resourceGroups/key-vault/providers/Microsoft.KeyVault/vaults/test1-keyvault-34",
              "keyVaultSecretName": "grewgrewrewhr"
          }
      }
       ```
 3. Confirm module version:
     ```PowerShell
    > Get-Module "Az.websites"
    
    ModuleType Version    PreRelease Name                                ExportedCommands
    ---------- -------    ---------- ----                                ----------------
    Script     2.11.4                Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppT…

    ```
4. Run Import-AzWebAppKeyVaultCertificate  to import the certificate
     ```PowerShell
    > Import-AzWebAppKeyVaultCertificate -ResourceGroupName "perf-test-ause" -WebAppName "server654376" -KeyVaultName "test1-keyvault-34" -CertName "grewgrewrewhr" - Debug
    ```
5. The debug output shows:
    - **Uri**
      - https://management.azure.com/subscriptions/#redacted#/resourceGroups/perf-test-ause/providers/Microsoft.Web/certificates/perf-test-ause-test1-keyvault-34-grewgrewrewhr?api-version=2021-01-15
    - **Payload:**
       ```
        Headers:
        x-ms-client-request-id        : 22ccd7a8-2f1d-4b56-a004-5551fc7b1e65
        Accept-Language               : en-US

        Body:
        {
          "properties": {
            "password": "",
            "keyVaultId": "/subscriptions/#redacted#/resourceGroups/key-vault/providers/Microsoft.KeyVault/vaults/test1-keyvault-34",
            "keyVaultSecretName": "grewgrewrewhr",
            "serverFarmId": "/subscriptions/#redacted#/resourceGroups/perf-test-ause/providers/Microsoft.Web/serverfarms/ASP-perftestause-a9d0"
          },
          "location": "Australia Southeast"
        }
       ```
    - **Response:**
       ```
        "ErrorEntity": {
        "ExtendedCode": "53008",
        "MessageTemplate": "Another certificate exists with same thumbprint {0} at location {1} in the Resource Group {2} with name {3}.",
       ```
   - **Error:** Import-AzWebAppKeyVaultCertificate: Object reference not set to an instance of an object.

## Expected
The command should be successful. This is how it functions if I were to first use 'Import-AzWebAppKeyVaultCertificate' to create the certificate link to app service, then repeat the command again.

## Actual 
The following error is returned:

        "ErrorEntity": {
        "ExtendedCode": "53008",
        "MessageTemplate": "Another certificate exists with same thumbprint {0} at location {1} in the Resource Group {2} with name {3}.",

Import-AzWebAppKeyVaultCertificate: Object reference not set to an instance of an object.

## Cause/Analysis
The 'Import-AzWebAppKeyVaultCertificate' does not allow for control over the 'name' parameter of 'https://learn.microsoft.com/en-us/rest/api/appservice/certificates/create-or-update'

You can see from the URI used for 'portal', that the name is 'test1-keyvault-34-grewgrewrewhr'.

When using PowerShell, the name is instead 'perf-test-ause-test1-keyvault-34-grewgrewrewhr'.

This mismatch in name means that 'Import-AzWebAppKeyVaultCertificate' is trying to create a new certificate association with the same thumbprint as an existing one, but with a different name.

I would expect 'Import-AzWebAppKeyVaultCertificate' to allow for the name to be specified as a parameter, similar to the REST API. 

Note that I can replicate this same error using the REST API, if I pass in the names above. 

## Note
This is also an issue between different versions of the 'Az.Websites' module, i.e. certificates created on version 2.8.2 of the module uses a different naming convention where the name is just the certificate name.

### Issue script & Debug output

```PowerShell
I have excluded full debug output as it may contain sensitive information. Please reach me internally on Teams for more detailed information.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     2.11.4                Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppT…
```

### Error output

```PowerShell
"ErrorEntity": {
        "ExtendedCode": "53008",
        "MessageTemplate": "Another certificate exists with same thumbprint {0} at location {1} in the Resource Group {2} with name 

Import-AzWebAppKeyVaultCertificate: Object reference not set to an instance of an object.
```

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
## Description
#19592 

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

File: src/Websites/Websites/Cmdlets/Certificates/ImportAzWebAppKeyVaultCertificate.cs [hunk 1]
```diff
@@ -99,7 +99,7 @@ public override void ExecuteCmdlet()
                 {
                     try
                     {
-                        kvc = WebsitesClient.CreateCertificate(ResourceGroupName, ResourceGroupName+'-'+KeyVaultName + '-'+CertName, certificate);
+                        kvc = WebsitesClient.CreateCertificate(ResourceGroupName, KeyVaultName + '-'+CertName, certificate);
```
Comment (msJinLei) [inline src/Websites/Websites/Cmdlets/Certificates/ImportAzWebAppKeyVaultCertificate.cs:102]:
```suggestion
                        kvc = WebsitesClient.CreateCertificate(ResourceGroupName, KeyVaultName + '-' + CertName, certificate);
```

**Review by msJinLei — CHANGES_REQUESTED** [review]

File: src/Websites/Websites/Cmdlets/Certificates/ImportAzWebAppKeyVaultCertificate.cs (hunk 1 above)
Comment (Kotasudhakarreddy) [reply src/Websites/Websites/Cmdlets/Certificates/ImportAzWebAppKeyVaultCertificate.cs]: Done the suggested changes.

**Review by msJinLei — APPROVED** [review]
