### PR TITLE
Fix for showing  on GET and persisting Tags on SET (if not given) for Database, Server and Elastic Pool

### LINKED ISSUE #1134: Set-AzureRmSqlDatabase does overwrite existing tags
When using the Set-AzureRmSqlDatabase cmdlet, existing tags get deleted even when Tags parameter is omitted.

release-1.0.0-preview

### PR DESCRIPTION
**Pull request by vaishali33**
## Description

Fix for showing  on GET and persisting Tags on SET (if not given) for Database, Server and Elastic Pool.
Also fixed Set-AzureRmSqlServer if SqlAdministratorPassword is not provided.

Fixes #1134 :Fetching Tags from Get-AzureRmSqlDatabase to set Tags values in set-AzureRmSqlDatabase if not provided

---

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md).**
- [ ] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyPSHelp-documentation.md).**
- [ ] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/dev/documentation/breaking-changes.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.
- [ ] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [ ] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change).
- [ ] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThrough` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [ ] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [ ] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [ ] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vaishali33__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vanark). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

File: src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/SetAzureSqlDatabase.cs [hunk 1]
```diff
@@ -113,7 +113,7 @@ protected override IEnumerable<AzureSqlDatabaseModel> ApplyUserInputToModel(IEnu
                 Edition = Edition,
                 MaxSizeBytes = MaxSizeBytes,
                 RequestedServiceObjectiveName = RequestedServiceObjectiveName,
-                Tags = TagsConversionHelper.CreateTagDictionary(Tags, validate: true),
+                Tags = this.MyInvocation.BoundParameters.ContainsKey("Tags") ? TagsConversionHelper.CreateTagDictionary(Tags, validate: true) : model.FirstOrDefault().Tags,
```
Comment (jaredmoo) [inline src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/SetAzureSqlDatabase.cs]: If `.FirstOrDefault` returns null, `.Tags` will throw NullRefException. I think that model should always have exactly one element here, if this is correct then use `Single` instead of `FirstOrDefault`

Comment (jaredmoo) [inline src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/SetAzureSqlDatabase.cs]: Since this line is a little complicated and is repeated several times, I suggest extracting it as a common method

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist.

File: src/ResourceManager/Sql/Commands.Sql/Server/Cmdlet/SetAzureSqlServer.cs [hunk 2]
```diff
@@ -95,12 +95,13 @@ protected override IEnumerable<Model.AzureSqlServerModel> ApplyUserInputToModel(
         {
             // Construct a new entity so we only send the relevant data to the server
             List<Model.AzureSqlServerModel> updateData = new List<Model.AzureSqlServerModel>();
+
```
Comment (markcowl) [inline src/ResourceManager/Sql/Commands.Sql/Server/Cmdlet/SetAzureSqlServer.cs]: remove extra line

**Comment by markcowl** [comment]
@vaishali33 Please respond to review comments, please read and fill out the checklist.

File: src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/SetAzureSqlDatabase.cs (hunk 1 above)
Comment (vaishali33) [inline src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/SetAzureSqlDatabase.cs]: I see that we are using .FirstOrDefault in code everywhere. Will do the changes and submit iteration.

**Comment by shahabhijeet** [comment]
@vaishali33 please address the PR. Code complete is next week.

File: src/ResourceManager/Sql/Commands.Sql/Server/Cmdlet/SetAzureSqlServer.cs (hunk 2 above)
Comment (vaishali33) [inline src/ResourceManager/Sql/Commands.Sql/Server/Cmdlet/SetAzureSqlServer.cs]: done.

**Comment by vaishali33** [comment]
@markcowl and @shahabhijeet I have addressed the comments and added tests. Please review. Thank you!

File: src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/SetAzureSqlDatabase.cs (hunk 1 above)
Comment (jaredmoo) [inline src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/SetAzureSqlDatabase.cs]: If you know that the collection is non-empty, then using `FirstOrDefault()` is just confusing to the reader - use `First()` instead.

The exact same code in 3 places is enough justification to extract method. It can be in utility class or base class, your choice. The fact that the code is complex enough to have a bug once (this time) means that it's complex enough to have a bug again, and when that happens the fix should only be done in one place.

Comment (vaishali33) [inline src/ResourceManager/Sql/Commands.Sql/Database/Cmdlet/SetAzureSqlDatabase.cs]: Comments addressed.

**Comment by jaredmoo** [comment]
Thanks for the changes Vaishali, LGTM!
